### ISSUE TITLE
Show coming movies

### ISSUE THREAD

**Issue by MadeleineDahlqvist** [ANschoolacc/Uppgift-2-En-biograf-sajt#13]
Show the 5 coming movies on homepage.
A link is also directed to all coming movies.

User is on homepage,
User clicks on a movie or link to all coming movies,
Page updates and shows movie or all coming movies

**Comment by MickeMarten** [comment]
Testing is done. @ConnyPettersson fixed small error inside class-code.
Moving card to done.
