### ISSUE TITLE
Create JSON-file for movies

### ISSUE THREAD

**Issue by ConnyPettersson** [ANschoolacc/Uppgift-2-En-biograf-sajt#14]
Create a JSON file with all the informations about the movies. 
We will copy the information from https://kino.nu/ and add it as objects in the JSON. 
The objects should contain the following keys: category, title, description, age-limit and rating.
Create 13 objects with movie properties, inside a loop.

**Comment by MickeMarten** [comment]
Added - isNew, ID and isReleased to json-object aswell.
