### ISSUE TITLE
Show top 3 movies

### ISSUE THREAD

**Issue by MadeleineDahlqvist** [ANschoolacc/Uppgift-2-En-biograf-sajt#15]
Show the top 3 movies playing on homepage.
A link is also directed to movie top list.

User is on homepage,
User clicks on a movie or link to movie top list,
Page updates and shows movie or movie top list

**Comment by MickeMarten** [comment]
This issue looks good on the main-branch.
Consider it done!

**Comment by MickeMarten** [comment]
Or atleast it did. When I reloaded the page, the top 3 movies disapeared.
I know you had discussions about this issue.

**Comment by oskber** [comment]
It is fixed now
